### ISSUE TITLE
Server Side Rendering Guide

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#1035]
Create a server-side rendering guide, and use React as the example. This will build a server-rendering app using React with incremental rendering, and done-ssr 1.2.0-beta, using zones as the glue mechanism.

The guide will go under Guides on donejs.com. This issue tracks not-so-smooth aspects of this, as @BigAB will be working on it some as well.

**Comment by matthewp** [comment]
> This is being actively updated.

# Issues

* [ ] - Docs don't appear on the donejs site. Why!?
* [x] - React's build process creates hashes in the file names, so something like `main.js` becomes `main-2dfs23ff.js`. So if you write some HTML to include this module... you have to know what the hash is going to be. Right now I'm just hard-coding the hash in but that is bad for obvious reasons. Need a better way.
* [x] - The `render` function does manual DOM manipulation. Would be better to be `document.innerHTML = `...`. 
* [x] - Not currently using can-zone-jsdom. Would prefer to switch to that (might be some issues?)
  * [ ] - Fill out the readme for can-zone-jsdom: https://github.com/canjs/can-zone-jsdom

**Comment by matthewp** [comment]
# Branch

https://github.com/donejs/donejs/tree/ssr-zones

# Guide

**docs/guides/react-ssr.md**

**Comment by matthewp** [comment]
After talking about the guide with @justinbmeyer and @BigAB we decided to make a change to incremental rendering reattachment to make it done automatically without development interaction. These issues track changes we are working on:

# Issues

* [x] - [Prevent evaled code in can-zone-jsdom](https://github.com/canjs/can-zone-jsdom/issues/6) from being leaking global variables.
* [x] - [Make pushMutations Zone capable of doing reattachment](https://github.com/donejs/done-ssr/issues/365)
* [x] - [Allow zones/steal to re-execute the main module each time the zone runs](https://github.com/donejs/done-ssr/issues/368)

**Comment by frank-dspeed** [comment]
@matthewp idea about loading of iles with dynamic names via a smal loader file that requires the hashed file name.

```<script src="requiring.js">```
