### ISSUE TITLE
DoneJS 3.0

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#1098]
- CanJS 5.0 with Treeshaking and can-query
  - docs 
  - Wrap `//steal-remove-start` with `if(ENV === prod)` stuff
- Steal w/ Treeshaking
- DoneJS 3.0
   - [x] incremental rendering
   - [ ] example apps
   - [x] generators
   - [x] guides updated, tested, etc (show new routing stuff)
   - [x] features, APIs

**Comment by matthewp** [comment]
Should we use [can-zone-jsdom](https://github.com/canjs/can-zone-jsdom) as the default DOM implementation?

**Comment by matthewp** [comment]
This can be used to get a local ssl certificate, which we need for h2: https://github.com/davewasmer/devcert/

**Comment by mjstahl** [comment]
In regards to the local ssl cert stuff, if we plan to force HTTPS, we should make accommodations for anyone using proxies like ngrok.

This can be a simple check for the existence of the `'x-forwarded-proto'` header or `req.connection.encrypted` (where `req` is a NodeJS Http Request). If either are true don't redirect to HTTPS.

**Comment by matthewp** [comment]
# Release list

## Merge to master

- [x] [done-ssr](https://github.com/donejs/done-ssr/pull/606)
- [x] [done-ssr-middleware](https://github.com/donejs/done-ssr-middleware/pull/66)
- [x] [done-serve](https://github.com/donejs/done-serve/pull/143)
- [x] [generator-donejs](https://github.com/donejs/generator-donejs/pull/298)
- [x] donejs-cli
- [ ] donejs

## Release

- [x] done-ssr
- [x] done-ssr-middleware
- [x] done-serve
- [x] generator-donejs
- [x] donejs-cli
- [ ] donejs

**Comment by justinbmeyer** [comment]
@matthewp this can be closed right?

**Comment by matthewp** [comment]
Yep.
