### ISSUE TITLE
Guide Notes

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#456]
0.6.0 Priority issues:
- [x] - https://github.com/donejs/place-my-order-api/issues/4 - Warnings P(3)
- [x] - https://github.com/donejs/place-my-order-api/issues/5 - API doesn't work. P(0)
- [ ] - https://github.com/stealjs/steal/issues/547 - Hot module swapping bug P(2)
- [ ] - `<pmo-header page="{page}"></pmo-header>` - use the right binding syntax P(3)
- [ ] - State can be blank in the demo page P(2) ![localhost_8080_src_restaurant_list_list_html](https://cloud.githubusercontent.com/assets/78602/12162672/ec2ef0b0-b4ca-11e5-929d-3b77ca140723.png)
- [x] - `($change)="{order.items.toggle this}"` `#restaurant="{value}"` P(3)
- [x] - http://donejs.com/place-my-order.html#section=section_Writethetemplate1 Adding the template breaks the app. P(0)
- [x] - #463 Socket connection P(0)
- [x] - list.component should use new bindings
- [ ] - Remove `# place-my-order` in `index.md`. P(3)
- [ ] - Change `## <pmo-order-new>` to  `## Use` P(4)
- [x] - `util/domless` is in production build P(2). 
      `+ can@2.3.8#util/domless/domless`
- [x] - 404 errors https://github.com/stealjs/system-npm/issues/92 P(1)
- [x] - Update guide to include setting up github at CI step. #464 P(1)
- [ ] - Update the deploy guide #465 P(1)
- [x] - Inline Cache Not working #466 P(2)
- [ ] - Server-side live reload wasn't working on order-history page. P(2)

**Comment by justinbmeyer** [comment]
- code highlight adding of the assets `<can-import>`
- Replace AppMap with AppViewModel
- `<p><a class="btn" href="/restaurants" role="button">Choose a Restaurant</a></p>` - the href is not using {{routeUrl}}
- I wonder if we should have them stick the `<pmo-home>` in the template right away ... just to see it in action.
- `Here we use can-href to create li` - it's not using can-href. There's multiple links to can-href 
- `After reloading the homepage` - homepage reload is not necessary.
- Is `import QUnit from 'steal-qunit';` necessary in `test.js`?
- `before_install sets up a window system to run Firefox.` what does this mean?
- We have them do travis before setting up github?
- indention weirdness in _details.component_ `{{/value}}\\n{{/if}}`
- probably can use `if` instead of `{{#switch action}}`
- At _Importing other projects_ we should probably let people know they can actually navigate to the tabs.
- `saveStatus: { Value: Object },` - why?
- `api/cities` needs a starting `/`
- `let Order` instead of `const Order = Map.extend`?

**Comment by justinbmeyer** [comment]
new.stache that might work:

```
<can-import from="bit-tabs/unstyled"/>
<can-import from="place-my-order/order/details.component!" />

<div class="order-form">
  <restaurant-model get="{ _id=slug }">
    {{#if isPending}}
      <div class="loading"></div>
    {{else}}
      {{#value}}
        {{#if saveStatus.isResolved}}
          <pmo-order-details order="{saveStatus.value}"></pmo-order-details>
          <p><a href="javascript://" ($click)="startNewOrder">
            Place another order
          </a></p>
        {{else}}
          <h3>Order from {{name}}</h3>

          <form ($submit)="placeOrder">
            <bit-tabs tabs-class="nav nav-tabs">
              <p class="info {{^if order.items.length}}text-error{{else}}text-success{{/if}}">
                {{^if order.items.length}}
                  Please choose an item
                {{else}}
                  {{order.items.length}} selected
                {{/if}}
              </p>
              <bit-panel title="Lunch menu">
                <ul class="list-group">
                  {{#each menu.lunch}}
                    <li class="list-group-item">
                      <label>
                        <input type="checkbox"
                          ($change)="order.items.toggle(.)"
                          {{#if order.items.has(.)}}checked{{/if}}>
                        {{name}} <span class="badge">${{price}}</span>
                      </label>
                    </li>
                  {{/each}}
                </ul>
              </bit-panel>
              <bit-panel title="Dinner menu">
                <ul class="list-group">
                  {{#each menu.dinner}}
                    <li class="list-group-item">
                      <label>
                        <input type="checkbox"
                          ($change)="order.items.toggle(this)"
                          {{#if order.items.has(.)}}checked{{/if}}>
                        {{name}} <span class="badge">${{price}}</span>
                      </label>
                    </li>
                  {{/each}}
                </ul>
              </bit-panel>
            </bit-tabs>

            <div class="form-group">
              <label class="control-label">Name:</label>
              <input name="name" type="text" class="form-control"
                {($value)}="order.name">
              <p>Please enter your name.</p>
            </div>
            <div class="form-group">
              <label class="control-label">Address:</label>
              <input name="address" type="text" class="form-control"
                {($value)}="order.address">
              <p class="help-text">Please enter your address.</p>
            </div>
            <div class="form-group">
              <label class="control-label">Phone:</label>
              <input name="phone" type="text" class="form-control"
                {($value)}="order.phone">
              <p class="help-text">Please enter your phone number.</p>
            </div>
            <div class="submit">
              <h4>Total: ${{order.total}}</h4>
              {{#if saveStatus.isPending}}
                <div class="loading"></div>
              {{else}}
                <button type="submit"
                    {{^if canPlaceOrder}}disabled{{/if}} class="btn">
                  Place My Order!
                </button>
              {{/if}}
            </div>
          </form>
        {{/if}}
      {{/value}}
    {{/if}}
  </restaurant-model>
</div>
```

**Comment by matthewp** [comment]
I opened a separate issue for the 404 errors: https://github.com/donejs/donejs/issues/490

**Comment by justinbmeyer** [comment]
- Github
- An editor
- firefox
- XCode or https://developer.android.com/sdk/index.html
