### ISSUE TITLE
DoneJS 0.8.0 Release Checklist

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#580]
- [x] - Do releases of all subprojects in pre-release
- [x] - Release of donejs-cli 0.8.0
- [x] - Merge minor into master
- [x] - Release donejs 0.8.0
- [x] - Verify the site is updated
- [x] - Forum post with release notes 
- [x] - Update chat.donejs.com to use 0.8.0
- [x] - Update place-my-order.com to use 0.8.0

**Comment by matthewp** [comment]
Features:
- Sessions
- can-zone
- The Generator generator

**Comment by daffl** [comment]
We probably don't want to advertise the generator generator until the general `donejs add` functionality in `0.9`

**Comment by matthewp** [comment]
k
