### ISSUE TITLE
Getting Started Guide Notes

### ISSUE THREAD

**Issue by alexisabril** [donejs/donejs#67]
_Issue by **[justinbmeyer](https://github.com/justinbmeyer)** from Sunday Aug 09, 2015 at 21:40 GMT_
_Originally opened as https://github.com/donejs/donejs/issues/30_

---
# Closed Issues
- changing less breaks live-reload: https://github.com/donejs/donejs/issues/31
- changed AppState to AppViewModel: https://github.com/donejs/donejs/issues/32
- warn about route changes needing a server restart: https://github.com/donejs/donejs/pull/34
# Setup the project
- [x] space before folder name

```
Creating folder  place-my-order
Installing yeoman-environment
```
- [x] **Remove short name from generator (p0)**

I thought we already did this.  But we should certainly remove this before launch.  We should have people enter in their component's module and tag name when creating a component.
- [ ] **On a high level, what does the generator do?**

I think this section can be improved. I think things are installed first, and then the questions come ... couldn't hurt to present the guide that way.
- [ ] **Testee or Karma - Test runner**

Isn't Testee installed only at this point?  We should probably remove Karma for now.
- [ ] **Key your keywords (comma to split) (p3)**

This is phrased weird and doesn't have a colon (:) after it like all the other questions do. Issue #58 
- [ ] **The other questions can be skipped for now by hitting enter.**

The "src" folder MUST be skipped to pick their defaults right?  The other ones can be skipped.
- [ ] **we can see the following files:**

It might be better if we have the descriptions next to the source.  If not, at least in the section below, the `file` should be separated from the description with a hyphen.
- [x] **You can start both by running: donejs develp (p3)**

The user won't be within place-my-order at this point.  Should `donejs init` leave them there?  If not, we should tell them to `cd` into that folder.
- [ ] **Use testee to open dev page. (p3)** #19

Can we use `testee` to open this page for them?  That way they don't have to navigate there?
- [ ] **Nice warning /error if `npm start` fails. (p4)** #63.

I had another process on 8080.  A better error message would be nice. 
- [ ] **Warnings about asset helper:** #19

<img width="562" alt="cursor_and_place-my-order" src="https://cloud.githubusercontent.com/assets/78602/9157158/6c0fc432-3eb8-11e5-91f7-de490b98acce.png">
- [ ] **Try it by changing the message property in src/app.js. (p3)**

To what?  What should they expect?  A video or something would be good here.  Maybe they should change the styles too?
- [ ] **place-my-order@0.0.0 No README data (p3)** #64

We should generate a README with the basic commands used to develop the app / test / deploy / build / etc.
## Setup a service API
- [ ] **npm install place-my-order-api --save**

Should they do this in another console? To leave up the live-reload?
## Loading assets
- [ ] **Before we create the first files we also need to install the place-my-order-assets**

This is worded strangely.  First files?  We are really installing them and then loading them into our application.  We should let people know we don't want to bore them with creating the app's CSS.
- [ ] **Every DoneJS application consists of at least two files:**

I think this discussion should be put in the **Development mode** section.  That section already references these two concepts and asks people to change them.  I'd put something the following in development mode:

---

Before we move on, lets take a look at what we've setup.  First, open `src/index.stache`, this is the entry-point of your application. This is what is rendered on the server.  If you check your network tab you'll see `localhost:8080` sent back something like this:

```
<!doctype ....>
```

This template is also used to update the page when the template's data changes.

Every template needs data to render right?  The `src/app.js` file defines the data `src/index.stache` uses to render.  Go ahead and change the message property from `'Hello World!'` to `'Hello There!`.  Notice that your page changed automatically.

The data the template uses to render is called the template's `viewModel`.  `index.stache` imports its own view model with:

```
<can-import from="place-my-order/app" as="viewModel" />
```

This is why it can render the application viewModel's message with:

```
<h1>{{message}}</h1>
```

Most of the other lines of this template help setup dependency management. We will talk about this later.

---

With that gone, you can simply say to load those styles into the application, you just have to import them by adding:

```
<can-import from="place-my-order-assets" />
```
- [ ] **the main application file at src/app.js looks like this:**

It should also include the title property.  Should we rename AppState to `AppViewModel`?
- [x] **Adding place-my-order-assets errors: (p0)**

when I install it, I see:

<img width="1013" alt="place-my-order_ _bash_ _80x24_and_place-my-order_and_justin_ _bash_ _80x24" src="https://cloud.githubusercontent.com/assets/78602/9157362/5e507d84-3ec0-11e5-9d2b-49d662b30381.png">
## Starting the application
- [ ] **Now our application is good to go and we can start the server**

It's not really good to go and we had already started it.
- [ ] **We need to proxy the place-my-order-api server to /api**

Aren't we proxying `/api` to `place-my-order-api`?
- [ ] **scripti**

**Comment by alexisabril** [comment]
_Comment by **[justinbmeyer](https://github.com/justinbmeyer)** from Sunday Aug 09, 2015 at 23:23 GMT_

---

# Creating custom elements
- [ ] **A bit of overview and see examples quicker.**

In general, this section seems to not "show" the developer anything.  I might suggest simply putting the elements in `index.stache` so they can see them.

Also, a bit of overview of how these elements will connect together might be nice.
- [ ] **The concept of components is stated w/o an introduction.**

> One of the most important concepts in DoneJS is splitting up your application functionality into individual, self-contained modules. In the following section we will create different components for the homepage, the restaurant list, and the order history. After that, we will glue them all together using routes and the global application state.

It talks about modules, but then just says we will create different components.  What are components?  Also, I think we should call appstate the application view-model.

## Creating a homepage element
- [x] **home.component (p0)**

Should that be:

```
donejs generate component home.component pmo-home
```
- [x] **Tag name suggestion is strange.**

```
$ donejs generate component home.component
? The tag name of the component: (pmo-home.component) 
```

shouldn't that be `pmo-home`?  Or `home` once we drop needing the "short name".
- [x] **creates pmo-home.component.component**

> $ donejs generate component home.component
> ? The tag name of the component: pmo-home.component
>   create src/home.component.component

This also screws up the tag="pmo-home.component" property.
- [ ] **Use can-href?**

```
<a class="btn" href="/restaurants" role="button">Choose a Restaurant</a>
```

Should that have 

```
can-href="{page='restaurants'}"
```

## Create the order history element
- [x] **The generator has similar problems as with the homepage.**

## Creating a restaurant list element
- [x] **the generator is broken** (p0)

https://github.com/donejs/generator-donejs/issues/20
- [ ] **they can be easily re-used**

It's not so they can be easily reused. It's so that the component can be worked on, tested, in one place.  We should link to modlets here.
- [x] **can/component/component**

Should be

```
import Component from 'can/component/';
```

**Comment by alexisabril** [comment]
_Comment by **[justinbmeyer](https://github.com/justinbmeyer)** from Monday Aug 10, 2015 at 03:16 GMT_

---

# Setting up routing

## Create Routes
- [ ] **from a URL string to properties in our application state**

use _application view-model_.
- [x] **export default AppState; (p0)**

`export default AppState;` is listed twice.  Change `AppState` to `AppViewModel`.
- [x] **URL changes to `http://localhost:8080/restaurants?message=Hello+World!&title=place-my-order` (p0)**

This is probably because message and title are left in the AppViewModel.

https://github.com/donejs/generator-donejs/issues/19

## Adding a header element
- [ ] **route helper?**

What does rails use?  Something like the following?

```
<li class="{{#isCurrentRoute page='home'}}active{{/isCurrentRoute}}">
```

This might need more of a `{{#matchesCurrentRoute}}` or something because it doesn't have to be a full match.
- [ ] **add this to index.stache**

We should have the user add this.  So they can play around a bit.

## Create a loading indicator
- [ ] **This is still an element ...**

But we call it an indicator in the title.  This section needs to be explained much better.  How will this component be used.  Hopefully if you add in a bit of the loading, then circle back to adding this to clean things up.
- [ ] **With changing `src/loading.component` to:**

"With" doesn't make sense.  Change this to "Change `src/.." to.

## Switch between components
- [x] **Loading error (p0)**

My console says:

> Not allowed to load local resource: file:///Users/justin/dev/temp/place-my-order/node_modules/place-my-order-assets/images/loading.gif
- [ ] **I really think we need more of an ember style routing here for easier use.**

``` html
<can-route pattern="/">
  <can-import ...>
    <pmo-restaurant-list/>
  </can-import>
</can-route>
<can-route pattern="/restaurants">
  <can-route pattern="/"> <restaurants/> </can-route>
  <can-route pattern="/:slug">
    <can-route pattern="/"> <details/> </can-route>
    <can-route pattern="/order"> <order/> </can-route>
  </can-route>
</can-route>
```

**Comment by alexisabril** [comment]
_Comment by **[justinbmeyer](https://github.com/justinbmeyer)** from Monday Aug 10, 2015 at 03:50 GMT_

---

# Getting and Displaying Data from the Server

## Creating a restaurants connection.
- [ ] __"Creating a restaurants connection." has a period at the end of it. __

We should be consistent everywhere.  Please check.
- [ ] **Answer the question about the URL endpoint**

We need a better way to show what the answers should be.  Perhaps a screen shot?

Also, is "endpoint" the right word?  Should this be "What is the restful url"?

## Test the connection
- [ ] **Test the connection in the console.** #50

Perhaps:

``` js
System.import("place-my-order/models/restaurant").then(function(module){
  module.Restaurant.getList({}).then(function(restaurants) {
    console.log(restaurants.attr());
  });
});
```

## Add data to the page
- [x] **Live-reload is not working (p0)**

When I make these changes, the page does not update.

**Comment by alexisabril** [comment]
_Comment by **[justinbmeyer](https://github.com/justinbmeyer)** from Monday Aug 10, 2015 at 04:09 GMT_

---

# Creating a unit-tested view model

## Identify view model state
- [x] **Restaurant list model state image missing (p1)**

restaurant-list-state.png 
- [ ] **Wrong quotes on code.**

Use `"` not `”` copied from ppt.

## Create dependent models
- [ ] **available states**

This doesn't have the url after it like cities does.  Do we need the urls?
- [ ] **Set the URL to ... and for? (p2)**

This section looks strange.  We should clean it up.

## Implement view model behavior
- [ ] **Should we do test-driven development? It will probably more more sense what the properties are doing.**
- [x] __live-reload does nothing after this change (p0) __

## Create a test

### Fixtures: Create fake data
- [x] **Should fixtures be in the qunit file?  This is how I originally wrote it.**
- [ ] **Some default fixtures will be provided for every generated model.**

They will or are?
- [x] **fixtures.js should be in src/models/fixtures/fixtures.js (p0)**
- [x] **the fixtures/state.js file improvements (p0)**

It should look something more like:

```
store = fixture.store(statesFixture)

...
'GET /api/states': store.findAll
```

Should we use the one in can-connect?  And, should we update it with `getList` and `get` methods?
- [x] **fixtures/city.js is incorrect (p0)**

Similar improvements as with `state.js`.
- [x] **fixtures/restaurant.js is incorrect (p0)**

Similar improvements with `state.js`, but this one probably needs to use some set algebra and then will almost certainly need can-connect's fixture.

## Test the view model
- [x] **This has the same data that was made in the fixture.  (p0)**

I don't think we should show actually changing the fixture files.  We should pull this back to what it originally looked like.  Only a single test, just like in the presentation.
- [x] **Live binding isn't working. (p0)**

https://github.com/stealjs/live-reload/issues/5

For example, if I empty a test to:

```
QUnit.asyncTest('setting a state loads its cities', function() {
  QUnit.start()
});
```

## Write the template
- [ ] **highlighting**

It would be nice to highlight what is actually being changed.  Only the State / city select is really being added.  
- [ ] **`<div class='restaurants'>`**

Why does this div need to exist?  I'd imagine we can get rid of it.

## Update the demo page
- [x] **This is why we're updating the fixtures files. (p0)**

I'm not sure what to do about this.

Actually, I think we can export the store and use that to get the data in the tests.
- [ ] **Lets link to some image ... can be on another domain** (p3)

<img width="322" alt="cursor_and_localhost_8080_src_restaurant_list_list_html" src="https://cloud.githubusercontent.com/assets/78602/9216937/c2b5b402-4086-11e5-9ea2-f15527307784.png">
- [ ] **Conclusion**

We should talk a bit about the modlet pattern here if we didn't already.

**Comment by alexisabril** [comment]
_Comment by **[justinbmeyer](https://github.com/justinbmeyer)** from Monday Aug 10, 2015 at 05:11 GMT_

---

# Setup automated tests and continuous integration (CI)

## Creating a global test page
- [ ] **inaccurate title**

We don't create this test page.  
- [ ] **test.html**

Part of me feels this should be in the root folder so I can just go to `localhost/test.html`.

## Using a test runner
- [ ] **Color? (p3)**

I thought the test output would be reported in color?

## Setting continuous integration (Travis CI)
- [ ] **Should we say this is optional?**
- [ ] __(the most popular one probably Jenkins and) __

and?
- [ ] **We don't really tell people to create an account, or even post their code to github. #464 (p0)**
- [x] **Doesn't work (p0)**

Errors without:

```
addons:
  firefox: "39.0"
```

**Comment by alexisabril** [comment]
_Comment by **[justinbmeyer](https://github.com/justinbmeyer)** from Monday Aug 10, 2015 at 05:24 GMT_

---

## Nested routes
- [ ] **Is defaults object necessary?**

```
route(':page/:slug', { slug: null });
route(':page/:slug/:action', { slug: null, action: null });
```
- [ ] **Trim down content**

I think there's a lot here that could be said more tersely.

## Create additional components
- [x] **Fix with generator fix (p0)**

## Add to the main template
- [ ] **Had to restart the server for the client to work.  (p0)**

steal.js was loading as HTML.
- [x] **This doesn't work without [fix](https://github.com/canjs/can-connect/issues/18) to can-connect (p0)**
- [x] **Problem with nested paths and reloading (p0)**  cc @matthewp 

If you are on a page like _http://localhost:8080/restaurants/cow-restaurant_ and refresh, the path to steal.js is wrong.  This is because it's relative like:

```
<script src="node_modules/steal/steal.js"></script>
```

The generators need to be fixed so the path works no matter what URL is used.

Ideally, this should be able to work if the app is hosted at something like: _mydomain.com/apps/myapp_.  So using a path like: `<script src="/node_modules/steal/steal.js">` is not a long term solution.
- [x] **Refreshing `http://localhost:8080/restaurants/cow-restaurant` breaks** (p0)

I see the following:

<img width="826" alt="place_my_order" src="https://cloud.githubusercontent.com/assets/78602/9217257/b4fdee16-408a-11e5-9377-4138a2672e2f.png">

If I navigate there, it works, but not if I refresh once I'm there.  This is with restarting the server.

I figured it out ... the component needs to import the restaurant model!

https://github.com/donejs/donejs/commit/51cb50d2ecb59b7724cb3bd131b50aa8ce0850b3

**Comment by alexisabril** [comment]
_Comment by **[justinbmeyer](https://github.com/justinbmeyer)** from Wednesday Aug 12, 2015 at 05:54 GMT_

---

# Importing other projects
- [x] **installing bit-tabs blows up live-reload** (p0)

<img width="945" alt="cursor_and_place_my_order" src="https://cloud.githubusercontent.com/assets/78602/9217389/aa2bf012-408c-11e5-9409-b02113f2ddce.png">
- [x] **hitting dinner menu causes pushstate error** (p0) 

This is probably a bug with CanJS.

<img width="707" alt="cursor_and_place_my_order" src="https://cloud.githubusercontent.com/assets/78602/9217416/01dfb276-408d-11e5-84cb-e65c37cbd515.png">

**Comment by alexisabril** [comment]
_Comment by **[justinbmeyer](https://github.com/justinbmeyer)** from Wednesday Aug 12, 2015 at 06:03 GMT_

---

# Creating data

## Updating the order model
- [ ] **We haven't created an order model yet so this title is strange** (p3)
- [x] **using forEach instead of .each** (p1)

Does forEach live-bind? 

```
total: {
      get() {
        let total = 0.0;
        this.attr('items').forEach(item => total += parseFloat(item.attr('price')));
        return total.toFixed(2);
      }
    }
```
- [ ] **Price should be assigned the "number" type so it doesn't have to be floated here** (p1)

## Implement the view model
- [ ] **importing component/component** (p3)

This should be `component/`
- [ ] **one liner** (p3)

``` js
canPlaceOrder: {
      get() {
        return this.attr('order.items.length');
      }
    }
```
- [ ] **save status is unnecessary** (p2)

can-connect/can/map adds a .isSaving.  That, combined with .isNew, is all you need.

## Write the template
- [x] **Styles broken?** (p0) Issue: #62

This is what mine looks like:

<img width="621" alt="place_my_order" src="https://cloud.githubusercontent.com/assets/78602/9217667/14ec0baa-4090-11e5-96a8-3c55b60e12ac.png">
- [x] **Saving doesn't work** (p0)

Can't save because probably `id` property is set to `name` and not `_id`.

**Comment by alexisabril** [comment]
_Comment by **[justinbmeyer](https://github.com/justinbmeyer)** from Wednesday Aug 12, 2015 at 06:34 GMT_

---

# Set up a real-time connection

## Adding real-time events to a model
- [x] **no --save** (p0)
- [x] **when npm install is run, we get warnings like:** (p1)

<img width="790" alt="place_my_order" src="https://cloud.githubusercontent.com/assets/78602/9217852/392e3388-4092-11e5-86ff-7de97c783b45.png">

Do we need to tell them to restart?
- [ ] **tell people where to insert socket code** (p3)

## Update the template
- [x] **the page doesn't work** (p0)

It breaks in the client and on the server.  the following seems to be the problem:

```
import io from 'socket.io-client';
```

```
Potentially unhandled rejection [5] Error: Error loading "socket.io-client@1.3.6#lib/lib" at file:/Users/justin/dev/temp/place-my-order/node_modules/socket.io-client/lib/lib.js
Error loading "socket.io-client@1.3.6#lib/lib" from "place-my-order@0.0.0#order/new/new" at file:/Users/justin/dev/temp/place-my-order/src/order/new/new.js
ENOENT, open '/Users/justin/dev/temp/place-my-order/node_modules/socket.io-client/lib/lib.js'
```

This is because it's index.js is doing:

```
module.exports = require('./lib/');
```

how was this working before?

**Comment by alexisabril** [comment]
_Comment by **[matthewp](https://github.com/matthewp)** from Wednesday Aug 12, 2015 at 12:53 GMT_

----

#### Adding real-time events to a model

> when npm install is run, we get warnings like: (p1)

This is happening because of live-reload. This project doesn't have a system-config, but can does, so there is a System.configDependencies array in the memory. When it tries to reload "package.json!npm" (which i'm still a little unsure is possible or not) it then wants to load "system-config" which doesn't exist.  I think the temporary solution here is to stop the server at this point.

**Comment by alexisabril** [comment]
_Comment by **[matthewp](https://github.com/matthewp)** from Wednesday Aug 12, 2015 at 13:53 GMT_

----

I get errors the first time I tried to run documentjs:

```
> place-my-order@0.0.0 document /Users/matthew/Projects/pmo-app
> documentjs

Generating docs at docs

/Users/matthew/Projects/pmo-app/node_modules/documentjs/node_modules/q/q.js:126
                    throw e;
                          ^
Error: ENOENT, open '/Users/matthew/Projects/pmo-app/node_modules/documentjs/site/templates/99914b932bd37a50b983c5e7c90ae93b/layout.mustache'

npm ERR! place-my-order@0.0.0 document: `documentjs`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the place-my-order@0.0.0 document script.
npm ERR! This is most likely a problem with the place-my-order package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     documentjs
npm ERR! You can get their info via:
npm ERR!     npm owner ls place-my-order
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.3.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "run" "document"
npm ERR! cwd /Users/matthew/Projects/pmo-app
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/matthew/Projects/pmo-app/npm-debug.log
npm ERR! not ok code 0
Error: Could not run command npm run document
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/donejs/bin/donejs:91:23)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:820:12)
```

To fix I had to run:

```
rm -rf node_modules/documentjs/site/static/build/99914b932bd37a50b983c5e7c90ae93b
rm -rf node_modules/documentjs/site/templates/99914b932bd37a50b983c5e7c90ae93b
```

and then run again.

**Comment by alexisabril** [comment]
_Comment by **[alexisabril](https://github.com/alexisabril)** from Wednesday Aug 12, 2015 at 14:40 GMT_

----

https://github.com/donejs/donejs/blob/master/docs/guide.md#test-the-connection currently returns a connection refused error.

Server trace:

```
Live-reload server listening on port 8012
Received client connection
/Users/alexisabril/Projects/done-test/place-my-order/node_modules/can-ssr/node_modules/http-proxy/lib/http-proxy/index.js:119
    throw err;
          ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
```

**Comment by alexisabril** [comment]
_Comment by **[matthewp](https://github.com/matthewp)** from Wednesday Aug 12, 2015 at 14:42 GMT_

----

@alexisabril did you restart the server when you got that error?

**Comment by alexisabril** [comment]
_Comment by **[alexisabril](https://github.com/alexisabril)** from Wednesday Aug 12, 2015 at 14:45 GMT_

----

@matthewp Sure did. There seems to be a catch somewhere that allows the server to stay running(vs EXIT 1), however the page doesn't actually update without stopping/restarting the server. It's left in a broken, but running state after the above error.

**Comment by alexisabril** [comment]
_Comment by **[matthewp](https://github.com/matthewp)** from Wednesday Aug 12, 2015 at 14:49 GMT_

----

It's the way our "donejs develop" runs: https://github.com/donejs/generator-donejs/blob/master/app/index.js#L109  This launches the first command as a background task.  Sometimes killing the server doesn't kill the server task and i'm not sure why that is.

**Comment by alexisabril** [comment]
_Comment by **[daffl](https://github.com/daffl)** from Wednesday Aug 12, 2015 at 15:10 GMT_

----

The connection refused error happens if you don't have the API running (`donejs api`).

**Comment by alexisabril** [comment]
_Comment by **[daffl](https://github.com/daffl)** from Wednesday Aug 12, 2015 at 15:19 GMT_

----

Also, @alexisabril's `TypeError: undefined is not a function` error issue should be fixed now in the generator.

**Comment by alexisabril** [comment]
_Comment by **[matthewp](https://github.com/matthewp)** from Wednesday Aug 12, 2015 at 15:27 GMT_

----

shouldn't you do a new donejs release to update the generator version?

**Comment by alexisabril** [comment]
_Comment by **[matthewp](https://github.com/matthewp)** from Wednesday Aug 12, 2015 at 15:37 GMT_

----

found another bug in the generator, will do a release once i fix it

**Comment by alexisabril** [comment]
_Comment by **[alexisabril](https://github.com/alexisabril)** from Wednesday Aug 12, 2015 at 16:05 GMT_

----

@daffl "The connection refused error happens if you don't have the API running (donejs api)." - Server is running prior to the error:

```
helo-3:place-my-order alexisabril$ donejs develop

> place-my-order@0.0.0 develop /Users/alexisabril/Projects/done-test/place-my-order
> npm start & npm run live-reload


> place-my-order@0.0.0 live-reload /Users/alexisabril/Projects/done-test/place-my-order
> steal-tools live-reload


> place-my-order@0.0.0 start /Users/alexisabril/Projects/done-test/place-my-order
> can-serve --proxy http://localhost:7070 --port 8080
```

"Also, @alexisabril's TypeError: undefined is not a function error issue should be fixed now in the generator." - Awesome! It sounds like there were some issues with the generator, I'll wait for the next merge and try this section again.

**Comment by alexisabril** [comment]
_Comment by **[alexisabril](https://github.com/alexisabril)** from Friday Aug 14, 2015 at 18:26 GMT_

---
- [ ] [Building To NW.js](https://github.com/donejs/donejs/blob/master/docs/guide.md#building-to-nwjs) should have a full build.js to be consistent with the rest of the guide
- [ ] Running tests produce an error: http://screencast.com/t/puIrCbO0fllu
- [ ] `donejs test` will fail if Firefox is already open or if not installed
- [ ] Cordova/NW.js references should be linked to those projects
- [ ] _Next, if using pushstate routing, we need to update our routes to use hash-based routing because NW.js runs within the file protocol. If you haven't already installed steal-platform, do so now. Then in src/app.js module add the following condition_ This section is outlines a duplicate step from only one step prior
- [ ] `donejs init` doesn't create the file structure outlined in the guide: http://screencast.com/t/0pN4G5f0xR. Actual file structure has a different test setup(test directory & smoke.html which is unused)
- [ ] documentation section of the guide assumes the initial setup & files don't exist, however the generator creates them
- [ ] re-running donejs document after adding documentation in the guide creates the new docs, but doesn't update index.html with the new links
- [ ] formatting issue in "Building to IOS and Android" http://screencast.com/t/TgXIj5nUa
- [ ] Error will be reported on Cordova build section if an Android emulator doesn't exist. This is a non-issue in terms of completing the guide and would be similar if the IOS emulator didn't exist, however may not be clear to a new developer.
- [ ] App is non-responsive: http://screencast.com/t/EjjOe4sk

**Comment by daffl** [comment]
We can close this. Guide issues should be submitted as new issues now.
