### ISSUE TITLE
donejs add app  slow

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#783]
@frank-dspeed commented on [Sat Sep 10 2016](https://github.com/donejs/generator-donejs/issues/145)

Explore solutions to making `donejs add app` faster such as:
- [x] - dependency audit (after deciding https://github.com/donejs/donejs/issues/705)
- [x] - yarn
- [x] - caching npm modules from https://github.com/donejs/generator-donejs/issues/128
- [x] - progressively adding heavy features
  - [x] - https://github.com/donejs/donejs/issues/540
  - [x] - https://github.com/donejs/cli/issues/63

Original comment:

> The Command add app instalsl to long it trys to download donejs-cli that is included already global else the command wouldn't run the step needs to be bypassed

---

@marshallswain commented on [Sat Sep 10 2016](https://github.com/donejs/generator-donejs/issues/145#issuecomment-246114066)

It needs a local copy of the DoneJS-cli, but we need to implement a caching mechanism.  We have talked about setting it up so that it caches the packages during the first install, then you could do `donejs add app -c` or something like that to tell it to use the cached modules.  I definitely agree with you, though.  It is the worst part of the current user experience to wait for all of the packages to install.

---

@justinbmeyer commented on [Sat Sep 10 2016](https://github.com/donejs/generator-donejs/issues/145#issuecomment-246118607)

To expand on what Marshall said, I think that global clis are an anti pattern. If you've ever had two projects on two different grunt versions on the same computer, you'll know what I mean. 

This means creating a new project is expensive, but it also means multiple DoneJS project versions can exist on the same computer.

Sent from my iPhone

> On Sep 10, 2016, at 9:16 AM, Marshall Thompson notifications@github.com wrote:
> 
> It needs a local copy of the DoneJS-cli, but we definitely need to implement a caching mechanism. We have talked about setting it up so that it caches the packages during the first install, then you could do 'donejs add app -c' or something like that to tell it to use the cached modules. I definitely agree with you, though. It is the worst part of the current user experience to wait for all of the packages to install.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

---

@frank-dspeed commented on [Sat Sep 10 2016](https://github.com/donejs/generator-donejs/issues/145#issuecomment-246128904)

i say we should simply add a donejs create app --link parameter that will allow npm link the current global donejs-cli

thats just my 5 cents.

---

@frank-dspeed commented on [Wed Oct 12 2016](https://github.com/donejs/generator-donejs/issues/145#issuecomment-253191462)

on systems with a slow network or unstable network connection doneJS isn't even useable that can't be by design the goal. I packed it now up and simply edit the JSON and other Files via Search replace 

---

@marshallswain commented on [Wed Oct 12 2016](https://github.com/donejs/generator-donejs/issues/145#issuecomment-253250362)

@frank-dspeed I know exactly what you mean.  I swear my house has the only reliable internet connection within a two hour drive, so when I go anywhere else it really hurts to either start a new project or do generator work in general.

---

@frank-dspeed commented on [Thu Oct 13 2016](https://github.com/donejs/generator-donejs/issues/145#issuecomment-253483041)

I have a good idea how about simply publish done-cli with all its modules to github and then we download simply the tar on done-cli install? this way we could cache the tar if needed we could download the tar to a place like ~/.donejs

---

@justinbmeyer commented on [Thu Oct 13 2016](https://github.com/donejs/generator-donejs/issues/145#issuecomment-253500823)

We'd have to build that tarball everytime a dependency changed. Building this is doable but the problem with this idea is it wouldn't install dependencies based on the current user's npm. 

Sent from my iPhone

> On Oct 13, 2016, at 6:05 AM, Frank Lemanschik notifications@github.com wrote:
> 
> I have a good idea how about simply publish done-cli with all its modules to github and then we download simply the tar on done-cli install? this way we could cache the tar if needed we could download the tar to a place like ~/.donejs
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.

---

@frank-dspeed commented on [Thu Oct 13 2016](https://github.com/donejs/generator-donejs/issues/145#issuecomment-253537362)

hm ok then we need to code something to create the tar based on the system once and then use that ?

---

@frank-dspeed commented on [Thu Oct 13 2016](https://github.com/donejs/generator-donejs/issues/145#issuecomment-253537854)

Maybe something like on first done-cli install look into ~/.donejs whats in it if nothing we create a tar if there is something and no option (Version) Specificated if version is specificated we could look if that tar exists elese build it

---

@frank-dspeed commented on [Thu Oct 13 2016](https://github.com/donejs/generator-donejs/issues/145#issuecomment-253538266)

Could you list dependencys that would need rebuild or else as far as i know and saw there shouldn't be something in that needs custom build.

---

@frank-dspeed commented on [Wed Oct 26 2016](https://github.com/donejs/generator-donejs/issues/145#issuecomment-254562167)

My Final result is we should drop the npm install from the /generator used by donejs add app and simply create only the skeletton dir with the right package.json and yarn.lock file so the User is free to use what he has and whants to Install the generated app. via yarn install --flat, yarn install, npm install

If all agree with that i will make a pull request!

Alternativ would be to check if he has yarn installed and use that if it is else use npm 
or adding a prompt after skeletton created with do you whant to execute npm install yes or no.

*\* UPDATE **

Finaly i Found out that Installing the donejs-cli and generator per Project is useless overhead that adds a lot of useless stuff. We should move all Project generation to the generator-donejs so it can ask befor it creates the Project. This way we have a Single Place where we could implament even install switches like use yarn.

This can be Open till We Know what to do with donejs-cli and donejs

---

@phillipskevin commented on [Thu Jan 26 2017](https://github.com/donejs/generator-donejs/issues/145#issuecomment-275451599)

I ran [slow-deps](https://www.npmjs.com/package/slow-deps) on a new DoneJS 1.0 app. I think this can provide some useful info as we decide what to break out of the default app generator:

```
$ slow-deps
Analyzing 24 dependencies...
[====================] 100% 0.0s
-------------------------------------------------
| Dependency          | Time  | Size   | # Deps |
-------------------------------------------------
| documentjs          | 35.7s | 108 MB | 323    |
| testee              | 29.4s | 30 MB  | 309    |
| steal-tools         | 28s   | 42 MB  | 346    |
| generator-donejs    | 27.4s | 27 MB  | 342    |
| donejs-cli          | 25.8s | 22 MB  | 345    |
| donejs-deploy       | 19.4s | 35 MB  | 262    |
| done-serve          | 14.4s | 24 MB  | 140    |
| steal-less          | 7s    | 5.9 MB | 75     |
| steal               | 5.6s  | 17 MB  | 59     |
| can-fixture         | 3.3s  | 3.9 MB | 27     |
| done-component      | 3.2s  | 1.8 MB | 23     |
| done-autorender     | 2.9s  | 3.3 MB | 25     |
| can-connect         | 2.8s  | 3.8 MB | 26     |
| can-component       | 2.7s  | 1.8 MB | 22     |
| steal-stache        | 2.6s  | 2.9 MB | 23     |
| funcunit            | 2.3s  | 8.2 MB | 3      |
| can-stache          | 2.2s  | 1.4 MB | 18     |
| can-view-autorender | 1.9s  | 544 KB | 9      |
| can-route-pushstate | 1.8s  | 723 KB | 10     |
| can-route           | 1.6s  | 682 KB | 9      |
| can-define          | 1.4s  | 791 KB | 8      |
| steal-qunit         | 1.3s  | 569 KB | 2      |
| done-css            | 1.1s  | 456 KB | 1      |
| can-zone            | 848ms | 86 KB  | 0      |
-------------------------------------------------
Total time (non-deduped): 3m 44.6s
Total size (non-deduped): 343 MB
```

---

@justinbmeyer commented on [Thu Jan 26 2017](https://github.com/donejs/generator-donejs/issues/145#issuecomment-275452352)

Could you run this on the top 5 and post the results:

```
| documentjs          | 35.7s | 108 MB | 323    |
| testee              | 29.4s | 30 MB  | 309    |
| steal-tools         | 28s   | 42 MB  | 346    |
| generator-donejs    | 27.4s | 27 MB  | 342    |
| donejs-cli          | 25.8s | 22 MB  | 345
```

I'd like to see what's heavy of each of these.  

---

@phillipskevin commented on [Fri Jan 27 2017](https://github.com/donejs/generator-donejs/issues/145#issuecomment-275544828)

### documentjs:
```
--------------------------------------------------------
| Dependency                 | Time  | Size   | # Deps |
--------------------------------------------------------
| chokidar                   | 45.6s | 5.6 MB | 56     |
| steal-tools                | 24s   | 71 MB  | 301    |
| steal                      | 6.4s  | 22 MB  | 76     |
| less                       | 3.9s  | 15 MB  | 35     |
| can                        | 2.5s  | 11 MB  | 2      |
| documentjs-github-download | 2.2s  | 1.1 MB | 19     |
| fs-extra                   | 1.8s  | 294 KB | 15     |
| glob                       | 1.5s  | 146 KB | 9      |
| handlebars                 | 1.4s  | 1.7 MB | 4      |
| cross-spawn-async          | 1.3s  | 90 KB  | 6      |
| async                      | 1s    | 77 KB  | 0      |
| minimatch                  | 968ms | 113 KB | 2      |
| jquery                     | 966ms | 1.3 MB | 0      |
| md5                        | 929ms | 36 KB  | 3      |
| engine-dependencies        | 915ms | 66 KB  | 2      |
| lodash                     | 888ms | 975 KB | 0      |
| yargs                      | 884ms | 119 KB | 0      |
| q                          | 843ms | 93 KB  | 0      |
| esprima                    | 798ms | 215 KB | 1      |
--------------------------------------------------------
```

### testee:
```
-----------------------------------------------
| Dependency        | Time  | Size   | # Deps |
-----------------------------------------------
| launchpad         | 13.4s | 10 MB  | 78     |
| miner             | 7.4s  | 4.1 MB | 111    |
| istanbul          | 5.1s  | 6.5 MB | 54     |
| feathers          | 4.2s  | 4.0 MB | 51     |
| feathers-socketio | 3.7s  | 2.5 MB | 46     |
| mocha             | 2.8s  | 1.2 MB | 34     |
| testee-client     | 2.5s  | 2.4 MB | 28     |
| body-parser       | 2s    | 885 KB | 19     |
| lodash            | 1.5s  | 1.4 MB | 0      |
| feathers-memory   | 1.3s  | 251 KB | 6      |
| connect-injector  | 1.2s  | 264 KB | 5      |
| feathers-rest     | 1.1s  | 314 KB | 5      |
| path              | 1s    | 90 KB  | 3      |
| http-proxy        | 1s    | 77 KB  | 2      |
| useragent         | 931ms | 252 KB | 1      |
| mime-types        | 926ms | 181 KB | 1      |
| debug             | 901ms | 51 KB  | 1      |
| commander         | 897ms | 50 KB  | 1      |
| q                 | 838ms | 124 KB | 0      |
-----------------------------------------------
```

### steal-tools:
```
-------------------------------------------------
| Dependency          | Time  | Size   | # Deps |
-------------------------------------------------
| transpile           | 10.9s | 11 MB  | 160    |
| chokidar            | 6.4s  | 5.6 MB | 56     |
| steal               | 5.5s  | 17 MB  | 59     |
| yargs               | 3.6s  | 803 KB | 45     |
| traceur             | 2.1s  | 2.5 MB | 16     |
| steal-bundler       | 1.8s  | 411 KB | 18     |
| uglify-js           | 1.8s  | 1.7 MB | 18     |
| lodash              | 1.5s  | 1.4 MB | 0      |
| glob                | 1.5s  | 165 KB | 10     |
| through2            | 1.3s  | 165 KB | 9      |
| winston             | 1.2s  | 443 KB | 6      |
| clean-css           | 1.1s  | 1.1 MB | 1      |
| moment              | 1.1s  | 2.2 MB | 0      |
| fs-extra            | 1s    | 176 KB | 3      |
| engine-dependencies | 1s    | 66 KB  | 2      |
| bitovi-source-map   | 978ms | 154 KB | 1      |
| ws                  | 965ms | 141 KB | 2      |
| tmp                 | 868ms | 29 KB  | 1      |
| steal-parse-amd     | 829ms | 31 KB  | 0      |
| pdenodeify          | 771ms | 4.0 KB | 0      |
| urix                | 760ms | 6.4 KB | 0      |
| colors              | 760ms | 30 KB  | 0      |
| find-line-column    | 755ms | 5.1 KB | 0      |
| is-appveyor         | 754ms | 5.2 KB | 0      |
-------------------------------------------------
```

### generator-donejs:
```
-------------------------------------------------------
| Dependency                | Time  | Size   | # Deps |
-------------------------------------------------------
| yeoman-generator          | 26.4s | 27 MB  | 336    |
| lodash                    | 1.2s  | 859 KB | 0      |
| q                         | 922ms | 124 KB | 0      |
| validate-npm-package-name | 858ms | 17 KB  | 1      |
| lodash.upperfirst         | 777ms | 14 KB  | 0      |
| lodash-inflection         | 772ms | 36 KB  | 0      |
| semver                    | 769ms | 55 KB  | 1      |
-------------------------------------------------------
```

### donejs-cli:
```
------------------------------------------------
| Dependency         | Time  | Size   | # Deps |
------------------------------------------------
| yeoman-generator   | 26s   | 26 MB  | 342    |
| yeoman-environment | 7.2s  | 9.5 MB | 79     |
| cross-spawn-async  | 1.3s  | 90 KB  | 6      |
| commander          | 1.2s  | 50 KB  | 1      |
| q                  | 923ms | 124 KB | 0      |
| debug              | 917ms | 51 KB  | 1      |
| mkdirp             | 896ms | 48 KB  | 2      |
| steal-platform     | 882ms | 5.9 KB | 0      |
------------------------------------------------
```

---

@justinbmeyer commented on [Thu Jan 26 2017](https://github.com/donejs/generator-donejs/issues/145#issuecomment-275555609)

We're those only dev dependencies? Why does steal-tools depend on testee? @matthewcp

Sent from my iPhone

> On Jan 26, 2017, at 5:18 PM, Kevin Phillips <notifications@github.com> wrote:
> 
> documentjs:
> 
> --------------------------------------------------------
> | Dependency                 | Time  | Size   | # Deps |
> --------------------------------------------------------
> | steal-tools                | 23.7s | 71 MB  | 301    |
> | chokidar                   | 6.2s  | 5.6 MB | 56     |
> | steal                      | 6.2s  | 22 MB  | 76     |
> | connect                    | 5s    | 2.4 MB | 68     |
> | less                       | 3.6s  | 15 MB  | 35     |
> | mocha                      | 2.7s  | 1.2 MB | 34     |
> | can                        | 2.2s  | 11 MB  | 2      |
> | documentjs-github-download | 2.1s  | 1.1 MB | 19     |
> | fs-extra                   | 1.8s  | 294 KB | 15     |
> | glob                       | 1.4s  | 146 KB | 9      |
> | handlebars                 | 1.3s  | 1.7 MB | 4      |
> | cross-spawn-async          | 1.2s  | 90 KB  | 6      |
> | engine-dependencies        | 986ms | 66 KB  | 2      |
> | jquery                     | 965ms | 1.3 MB | 0      |
> | minimatch                  | 957ms | 113 KB | 2      |
> | md5                        | 930ms | 36 KB  | 3      |
> | qunit-mocha-ui             | 919ms | 58 KB  | 0      |
> | rimraf                     | 918ms | 31 KB  | 1      |
> | yargs                      | 911ms | 119 KB | 0      |
> | lodash                     | 881ms | 975 KB | 0      |
> | async                      | 839ms | 77 KB  | 0      |
> | q                          | 828ms | 93 KB  | 0      |
> | esprima                    | 797ms | 215 KB | 1      |
> --------------------------------------------------------
> testee:
> 
> -----------------------------------------------
> | Dependency        | Time  | Size   | # Deps |
> -----------------------------------------------
> | launchpad         | 11.7s | 10 MB  | 78     |
> | miner             | 7.1s  | 4.1 MB | 111    |
> | istanbul          | 4.5s  | 6.5 MB | 54     |
> | feathers          | 4.2s  | 4.0 MB | 51     |
> | feathers-socketio | 3.7s  | 2.5 MB | 46     |
> | jshint            | 3s    | 4.5 MB | 29     |
> | mocha             | 2.7s  | 1.2 MB | 34     |
> | testee-client     | 2.4s  | 2.4 MB | 28     |
> | body-parser       | 2.2s  | 885 KB | 19     |
> | del               | 2.1s  | 263 KB | 25     |
> | async             | 1.6s  | 1.9 MB | 1      |
> | lodash            | 1.4s  | 1.4 MB | 0      |
> | feathers-memory   | 1.3s  | 251 KB | 6      |
> | chai              | 1.2s  | 439 KB | 3      |
> | connect-injector  | 1.2s  | 264 KB | 5      |
> | feathers-rest     | 1.1s  | 314 KB | 5      |
> | path              | 1s    | 90 KB  | 3      |
> | http-proxy        | 959ms | 77 KB  | 2      |
> | useragent         | 928ms | 252 KB | 1      |
> | mime-types        | 921ms | 181 KB | 1      |
> | debug             | 915ms | 51 KB  | 1      |
> | commander         | 862ms | 50 KB  | 1      |
> | q                 | 859ms | 124 KB | 0      |
> | qunitjs           | 836ms | 178 KB | 0      |
> -----------------------------------------------
> steal-tools:
> 
> -------------------------------------------------
> | Dependency          | Time  | Size   | # Deps |
> -------------------------------------------------
> | testee              | 27.3s | 29 MB  | 318    |
> | transpile           | 11.5s | 11 MB  | 160    |
> | browserify          | 8.7s  | 6.8 MB | 119    |
> | chokidar            | 6.2s  | 5.6 MB | 56     |
> | steal               | 5.4s  | 17 MB  | 59     |
> | coveralls-send      | 5.2s  | 4.2 MB | 80     |
> | bower               | 4.9s  | 17 MB  | 1      |
> | istanbul            | 4.5s  | 6.5 MB | 54     |
> | yargs               | 3.7s  | 803 KB | 45     |
> | cssify              | 3.3s  | 2.1 MB | 46     |
> | jshint              | 3.1s  | 4.5 MB | 29     |
> | uglify-js           | 2.7s  | 1.7 MB | 18     |
> | mocha               | 2.6s  | 1.2 MB | 34     |
> | steal-bundler       | 2.2s  | 411 KB | 18     |
> | traceur             | 2.2s  | 2.5 MB | 16     |
> | serve-static        | 1.6s  | 311 KB | 19     |
> | through2            | 1.6s  | 165 KB | 9      |
> | rimraf              | 1.6s  | 182 KB | 12     |
> | connect             | 1.5s  | 207 KB | 10     |
> | lodash              | 1.4s  | 1.4 MB | 0      |
> | glob                | 1.4s  | 165 KB | 10     |
> | winston             | 1.2s  | 443 KB | 6      |
> | moment              | 1.1s  | 2.2 MB | 0      |
> | clean-css           | 1.1s  | 1.1 MB | 1      |
> | tmp                 | 1.1s  | 29 KB  | 1      |
> | mock-fs             | 1.1s  | 992 KB | 3      |
> | steal-qunit         | 1s    | 569 KB | 2      |
> | fs-extra            | 997ms | 176 KB | 3      |
> | comparify           | 990ms | 11 KB  | 0      |
> | jquery              | 980ms | 1.3 MB | 0      |
> | ws                  | 938ms | 141 KB | 2      |
> | engine-dependencies | 907ms | 66 KB  | 2      |
> | bitovi-source-map   | 906ms | 154 KB | 1      |
> | find-line-column    | 870ms | 5.1 KB | 0      |
> | steal-css           | 854ms | 378 KB | 0      |
> | steal-parse-amd     | 836ms | 31 KB  | 0      |
> | steal-conditional   | 783ms | 54 KB  | 0      |
> | pdenodeify          | 769ms | 4.0 KB | 0      |
> | mockery             | 768ms | 52 KB  | 0      |
> | tree-kill           | 768ms | 7.8 KB | 1      |
> | mocha-lcov-reporter | 753ms | 9.8 KB | 0      |
> | colors              | 752ms | 30 KB  | 0      |
> | urix                | 744ms | 6.4 KB | 0      |
> | is-appveyor         | 738ms | 5.2 KB | 0      |
> -------------------------------------------------
> generator-donejs:
> 
> -------------------------------------------------------
> | Dependency                | Time  | Size   | # Deps |
> -------------------------------------------------------
> | yeoman-generator          | 24.2s | 27 MB  | 336    |
> | donejs-cli                | 23.6s | 22 MB  | 345    |
> | coveralls-send            | 4.9s  | 4.2 MB | 80     |
> | istanbul                  | 4.6s  | 6.5 MB | 54     |
> | mocha                     | 2.1s  | 1.2 MB | 17     |
> | donejs                    | 1.9s  | 405 KB | 17     |
> | fs-extra                  | 1.8s  | 336 KB | 16     |
> | lodash                    | 1.2s  | 859 KB | 0      |
> | mkdirp                    | 883ms | 48 KB  | 2      |
> | validate-npm-package-name | 879ms | 17 KB  | 1      |
> | q                         | 842ms | 124 KB | 0      |
> | semver                    | 817ms | 55 KB  | 1      |
> | lodash.upperfirst         | 780ms | 14 KB  | 0      |
> | lodash-inflection         | 778ms | 36 KB  | 0      |
> | mocha-lcov-reporter       | 756ms | 9.8 KB | 0      |
> -------------------------------------------------------
> donejs-cli:
> 
> -------------------------------------------------
> | Dependency          | Time  | Size   | # Deps |
> -------------------------------------------------
> | documentjs          | 29.7s | 108 MB | 323    |
> | yeoman-generator    | 25.1s | 26 MB  | 342    |
> | yeoman-environment  | 5.8s  | 9.5 MB | 79     |
> | coveralls-send      | 5.6s  | 4.2 MB | 80     |
> | istanbul            | 4.7s  | 6.5 MB | 54     |
> | jshint              | 3s    | 4.5 MB | 29     |
> | mocha               | 2.1s  | 1.2 MB | 17     |
> | rimraf              | 1.7s  | 182 KB | 12     |
> | concat-stream       | 1.3s  | 178 KB | 9      |
> | cross-spawn-async   | 1.2s  | 90 KB  | 6      |
> | mkdirp              | 892ms | 48 KB  | 2      |
> | engine-dependencies | 892ms | 66 KB  | 2      |
> | commander           | 879ms | 50 KB  | 1      |
> | debug               | 877ms | 51 KB  | 1      |
> | is-ci               | 871ms | 16 KB  | 1      |
> | q                   | 829ms | 124 KB | 0      |
> | mockery             | 768ms | 52 KB  | 0      |
> | steal-platform      | 756ms | 5.9 KB | 0      |
> | mocha-lcov-reporter | 750ms | 9.8 KB | 0      |
> -------------------------------------------------
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

---

@phillipskevin commented on [Thu Jan 26 2017](https://github.com/donejs/generator-donejs/issues/145#issuecomment-275571119)

It's dependencies and devDependencies.

---

@frank-dspeed commented on [Fri Jan 27 2017](https://github.com/donejs/generator-donejs/issues/145#issuecomment-275641810)

I think in general this is one of the really big issues I was facing also I solved it via moving simply all can dependencies to peerDependencys that saves a lot of time also flat install algo and yarn work really great even a normal donejs installation utilizing yarn takes round about 15 sec on a normal desktop PC 

---

@frank-dspeed commented on [Fri Jan 27 2017](https://github.com/donejs/generator-donejs/issues/145#issuecomment-275641992)

donejs-cli can be dropped complete and replaced by donejs global installed that does the function relative to project dir.

In that case of deprecating donejs-cli we simply move some functions to the generator that will make sure to do the right stuff in case donejs-cli is there and maybe even a lot of more generators are a mighty thing we can let them handle all kind of version migrations based on conditions so we save the user from trouble we could even parse the code interactively with it and let the user choose if he wants to upgrade syntax interactive based on suggestions.

we can even split the generators into version related once so we make the generator install the right migration module for the version and so on.

---

@justinbmeyer commented on [Fri Jan 27 2017](https://github.com/donejs/generator-donejs/issues/145#issuecomment-275658307)

Can you do it with just deps? Those are what are installed by the CLI. 

Sent from my iPhone

> On Jan 26, 2017, at 7:59 PM, Kevin Phillips <notifications@github.com> wrote:
> 
> It's dependencies and devDependencies.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

---

@matthewcp commented on [Fri Jan 27 2017](https://github.com/donejs/generator-donejs/issues/145#issuecomment-275670319)

Hey @justinbmeyer, I think you may have meant @matthewp, not me! Thanks.

---

@phillipskevin commented on [Fri Jan 27 2017](https://github.com/donejs/generator-donejs/issues/145#issuecomment-275683500)

@justinbmeyer I updated https://github.com/donejs/generator-donejs/issues/145#issuecomment-275544828 to only have dependencies.

---

@matthewp commented on [Mon Jan 30 2017](https://github.com/donejs/generator-donejs/issues/145#issuecomment-276104481)

Going to move this into donejs/donejs and make it an epic.

**Comment by pYr0x** [comment]
we maybe can remove testee from steal, since it will not use testee anymore. we use saucelab instead

**Comment by matthewp** [comment]
@pYr0x that's a devDependency though, that should have no effect on `donejs add app`.

**Comment by pYr0x** [comment]
the devDependency are downloaded too if use `donejs add app` no?

**Comment by matthewp** [comment]
Steal's devDependencies are not, no.

**Comment by justinbmeyer** [comment]
We should make everything use the same version of steal/steal-tools

**Comment by phillipskevin** [comment]
documentjs is the only thing with an older version of steal in its `dependencies`.

**Comment by phillipskevin** [comment]
We've removed `donejs-deploy` and `documentjs` from generated apps. This cut the app size nearly in half (343 MB -> 177 MB). Is there anything more we want to do on this for 1.0 or can this be closed out? @justinbmeyer @matthewp

**Comment by matthewp** [comment]
I'm going to test donejs-chat today, will take note of any slowness and report back.

**Comment by matthewp** [comment]
Just inited a new app and it took about a minute. So really good!

**Comment by justinbmeyer** [comment]
@phillipskevin what's the "next thing" we could do?  How hard would it be?

Can you do a quick look at where we are now, and provide suggestions on how things could be improved and what the expected improvement might be?

My guess is that there's nothing "worth it" right now.  But it's good to know.  Thanks!

**Comment by phillipskevin** [comment]
After taking a look at what's left, the only other thing I think we could do that would have a significant impact is splitting `generator-donejs` into seperate generators. 

I detailed this here: https://github.com/donejs/donejs/issues/792.

The summary of this is that we could save about 12 MB of dependencies since we wouldn't have to install fixtures, components, and `can-connect`.

**Comment by justinbmeyer** [comment]
cool, lets close this issue then
