### ISSUE TITLE
DoneJS 1.1

### ISSUE THREAD

**Issue by phillipskevin** [donejs/donejs#787]

**Comment by frank-dspeed** [comment]
# Question about Networking
I have a little design Question as a Network Engineer i am wondering about how you overcome this fact
That a Stream that not ends will simply make the Site load as long as you stream.

## Little Importent base knowleg about TCP/IP -> HTTP Implamentation 
Dependencys inharitance the express -> http -> net

## The Problem with write Streams
When you write out some data via a stream to the direct net socket (The Browser Connection)
The Page is only loaded after you sended a end so the page will load until you end that is slow
i think loading that async as webcomponent bypasses all that limits and also your iframe way for syncing up the dom.

Fact:
a webcomponent returns a HTML Document like a iframe

I Think at present you want to render a Iframe to bypass that? and Stream to the iframe right?

## Some More example code about sending files to a browser

```
//sendStream
function sendFileStream(req, res, path, opts) {
      // create send stream
    var stream = send(req, path, opts)

    // add directory handler
    stream.on('directory', onDirectory)

    // add headers listener
    if (setHeaders) {
      stream.on('headers', setHeaders)
    }

    // add file listener for fallthrough
    if (fallthrough) {
      stream.on('file', function onFile () {
        // once file is determined, always forward error
        forwardError = true
      })
    }

    // forward errors
    stream.on('error', function error (err) {
      if (forwardError || !(err.statusCode < 500)) {
        next(err)
        return
      }

      next()
    })

    // pipe
    stream.pipe(res)
}
//sendFile Kernel method
var open = process.binding('fs').open;
var sendfile = process.binding('fs').sendfile;
var bufSz = 1 << 10;
function sendfileKernel(req, path) {
  open(path, process.O_RDONLY, 0, function(err, fd) {
        // Track our offset in the file outside of sendData() so that its value
        // is stable across multiple invocations
        var off = 0;
        var s = req.connection
        var sendData = function() {
            // We only care about the 'drain' event if we're not done yet
            s.removeListener('drain', sendData);

            try {
                // Try to send file data until we either hit EOF, or fail the
                // write due to EAGAIN
                do {
                    nbytes = sendfile(s.fd, fd, off, bufSz);
                    off += nbytes;
                } while (nbytes > 0);

                s.end();
            } catch (e) {
                // Only EAGAIN is special; everything else is fatal
                if (e.errno !== process.EAGAIN) {
                    throw e;
                }

                // When the socket has room for more data, start pumping again
                s.on('drain', sendData);

                // Manually fire up the IOWatcher so that the 'drain' event
                // fires. The net.Stream class usually manages this for you,
                // but since we're going around it via sendfile(), we have to
                // do this manually.
                s._writeWatcher.start();
            }
        };

        if (err) {
            console.error(err);
            s.end();
            return;
        }

        // Kick off the transfer
        sendData();
    });
}
```

**Comment by matthewp** [comment]
@frank-dspeed this is not the issue to bring up such questions.

**Comment by matthewp** [comment]
# Release process

All of these need to be released, along with release notes

* [x] - done-ssr
* [x] - done-ssr-middleware
* [x] - done-serve
* [x] - done-autorender
* [x] - donejs-cli
* [x] - [bit-docs-donejs-theme](https://github.com/donejs/bit-docs-donejs-theme) (including updating the dropdown to include the ssr react guide)
  * [x] - update donejs/donejs to use the new theme version
* [x] - donejs

Then need to make sure to also:

* [x] - Really good release notes for donejs/donejs
* [x] - Release new version of the website
* [x] - Marketing for the new react guide

**Comment by matthewp** [comment]
This was released.
