### ISSUE TITLE
DoneJS 1.0 Release Checklist

### ISSUE THREAD

**Issue by phillipskevin** [donejs/donejs#788]
This issue is to keep a list of steps that need to be done when DoneJS 1.0 is ready to be released.

### Make it possible to install specific versions of plugins
- [X] https://github.com/donejs/donejs/issues/854

### Deploy the donejs#major site
- [x] deploy this https://donejs.github.io/donejs-next/

### Update donejs#master so site continues to use DoneJS 0.9.2
- [x] https://github.com/donejs/donejs/issues/855

### Update donejs-mocha for 1.0
- [x] https://github.com/donejs/donejs-mocha/issues/8

### Create `-legacy` branch and merge `major` into `master`

- [x] donejs
- [x] donejs-cli
- [x] generator-donejs
- [x] done-autorender
- [x] done-ssr
- [x] done-ssr-middleware
- [x] done-serve

### Release 1.0.0 final versions (remove `-alpha.x`)

- [x] donejs
- [x] donejs-cli
- [x] generator-donejs
- [x] done-component
- [x] done-autorender
- [x] done-ssr
- [x] done-ssr-middleware
- [x] done-serve
- [x] donejs-nw
- [x] donejs-electron
- [x] donejs-cordova
- [x] steal-nw
- [x] steal-cordova
- [x] bit-tabs
- [x] done-css
- [x] donejs-mocha

### Other
- [x] remove `-alpha` from dependencies / devDependencies of all the donejs projects
- [x] update guides and guides' tests to not install `@alpha` versions
- [x] [set up greenkeeper](https://github.com/donejs/donejs/issues/475)

**Comment by matthewp** [comment]
The only remaining item is to flip donejs-next to be donejs.com.

**Comment by chasenlehara** [comment]
Site’s been published! 👯
