### ISSUE TITLE
Proposal: Streamable apps

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#834]
# Proposal: Stream-able apps

This proposal seeks to add streaming abilities to DoneJS, providing an improved user experience.  By streaming, we mean we are able to write HTML out to the user as soon as we have the data for it. Instead of waiting for all the data to return from the database or a service call, we are able to stream records as they are retrieved into meaningful output to a user.  Specifically, we seek to enable streaming during initial rendering (SSR) and also once the browser has loaded.

This should have a significant impact on performance, especially SSR performance.  When rendering an HTML page on the server, we will be able to stream out the `<head>` immediately which typically includes `<link>` tags that load external resources.  Getting that HTML to the browser immediately, means that the browser can start loading those resources while the database is still hypothetically returning data. 

## SSR flow

![streaming-ssr](https://cloud.githubusercontent.com/assets/78602/23108548/7abcbaaa-f6d4-11e6-9d18-d4c7c947b25f.gif)

## Overview of streaming flow

1. Browser makes a request to the `todos.html` page.
2. __SSR server__ begins rendering an instance of the application.
3. `<head>{{title}}</head>` and `<link href=“theme.css”>` are not waiting on anything asynchronous, so they are streamed to the HTML result.
4. The `<ul>` (probably) isn't waiting on any asynchronous behavior, so it is streamd to the result.
5. The `{{#each todosPromise.value}}` does the following:
   1. Does a request for `Todo.getList({})` which results in a promise that resolves immediately to a `DefineList`.
   2. This fires off a `.fetch()` request to `/api/todos.ndjson` whose results will be streamed to that `DefineList`.  
   3. That `DefineList` is passed to `can-view-live.list`.
   4. The `DefineList`, `can-view-live.list` and the __streaming DOM serializer__ are able to coordinate in such a way to notify the DOM serializer to wait.
6.  __Services server__ handles the `/api/todos.ndjson` request.
7.  __Services server__ gets a pooled connection and makes a `SELECT` query to the database.
8.  _As records come back_, the __services server__ converts them into newline delimited JSON, and writes the records in chunks back to the __SSR server__.
9. The __SSR server__ parses out the new `JSON` records, `.push()` each record into the `DefineList`.
10. By adding the record into the `DefineList`, a new `<li>` is created
11. The __streaming DOM serializer__ is able to identify this change, serialize the DOM of the `<li>` and `res.write` it to the browser.
12. The browser displays the contents of the  `<li>`.

Steps 8-12 repeat _as records come back_ from the Database.

Once the database records have completed:

1. The __Services server__ response wil be ended `res.end()`.
2. The asynchronous behavior associated with the DefineList will complete.
3. `can-view-live.list` will mark all of its nodes as being ready for serialization.
4.  The __streaming DOM serializer__ will move onto the closing `</ul>`.
5.  The __SSR server__ will write out the closing `</ul>` to the browser.

 
## Things to build

- [ ] - [A `ndjson` stream transformer](https://github.com/canjs/can-ndjson-stream/issues/1):
  ```js
  fetch("todos.ndjson") .then( (response) => {   
   return ndjsonStream( response.body  );
   }).then( (todosStream) => {    });
  ```
- [ ] - [A streaming can-connect behavior](https://github.com/canjs/can-connect-ndjson/issues/1):
  ```js
  // get a streaming list of todos
  Todo.getList({}).then(function(todos){
    template({ todos: todos });
  });
  ```
  ```html
  <!-- template updates as todos are returned -->
  <ul>
    {{#each todos}}
      <li>{{name}}</li>
    {{/each}}
  </ul>
  ```
- [ ] - [A streaming DOM serializer](https://github.com/donejs/vdom-streaming-serializer/issues/1):
  ```js
  var serialize = require('vdom-streaming-serializer');
  http.createServer(function(request, response){
  
    var document = makeDocument();

    // ... ADD APP TO DOCUMENT ...
    myApp(document);
  
    // send back HTML as it is "completed"
    var stream = serialize(document.documentElement);
    stream.pipe(response);
  
  });
  ```
- [ ] - [A notification mechanism for asynchronous and/or streaming behavior](https://github.com/canjs/can-observation-zone/issues/1):
  ```js
  var observationZone = require("can-observation-zone");

  // A stateful object
  var todos = new DefineList([
    {id: 1, name: "lawn"}
  ]);
  
  // Indicates the length is going to change in the future
  var updatedTodos = observationZone.add(todos, "length");
  
  var completed = observationZone.completed(todos,"length");
  completed.then(function(){
    console.log("zone is completed");
  })
  
  setTimeout(function(){
    todos.push({id: 2, name: "dishes"});
    updatedTodos();
    console.log("updatedTodos")
  },1);
  
  // logs
  //  - updatedTodos
  //  - zone is completed
  ```
- [ ] - [Streaming aware live-binding utilities](https://github.com/canjs/can-view-live-streamable/issues/1)
- [ ] - [A demo app that puts it all together](https://github.com/donejs/demo-streaming-dev-server/issues/1)

```shell
donejs-streaming-dev-server
```

## Links

- [CSV + fetch streaming example](https://jakearchibald.com/2015/thats-so-fetch/) [JSBin](https://output.jsbin.com/gowaze/quiet)
- [NDJson](https://jakearchibald.com/2016/fun-hacks-faster-content/)
- [postgresql and node](http://mherman.org/blog/2015/02/12/postgresql-and-nodejs/#.WKog5EUrJTY)
- [streams and express](http://stackoverflow.com/questions/25206141/having-trouble-streaming-response-to-client-using-expressjs) - actually done with [http.ServerResponse](https://nodejs.org/api/http.html#http_class_http_serverresponse)

**Comment by matthewp** [comment]
Sounds good overall. Only point I have an issue with is `5.i`:

> Does a request for Todo.getList({}) which results in a promise that resolves immediately to a DefineList.

I don't think this is the best approach, especially given later we need to know that the list is complete:

> The asynchronous behavior associated with the DefineList will complete.

How will a user know that the asynchronous behavior is complete if the problem doesn't resolve after it is complete?

I think it would be more approach to create a behavior that adds a `getListStream` method. This would be the stream equivalent of `getList`; it would return a stream where each item in the stream is an instance of the Map type.

**Comment by justinbmeyer** [comment]
I don't think this would work with the rest of canjs well. Things like sets depend on an physical list type.

I talked about how async could work and know when the list is complete.

**Comment by matthewp** [comment]
Good point. So what we really need is a way to represent the list _and_ the stream. It's just a matter of figuring out the best api to do that.

### getListStream -> Promise<ListResponse>

One way would be to create a new Type similar to what fetch does. So maybe it would be something like:

```js
Type.getListStream().then(function(resp) {
  resp; // { list, stream, promise }
});
```

This is a little odd because it is named getListStream but returns a Promise. I suppose getList doesn't return what its named either...

### getListStream -> Stream

Another option is to put the List type on the stream itself:

```js
var stream = Type.getListStream();

stream.list; // -> DefineList
```

Not sure if there's precedent for this sort of API.

### getList -> Promise<List>

Similar to your proposal, but putting the stream on the List instance so its accessible:

```js
Type.getList().then(function(list){
  list.stream; // -> Stream
});
```

This would make it easy to use within a viewModel sorta like we do with Promises:

```js
var VM = DefineMap.extend({
  get todosPromise() {
    return Todo.getList();
  }

  get todosStream(lastVal, resolve) {
    this.todosPromise.then(function(todos){
      resolve(todos.stream);
    });
  }
});
```

**Comment by matthewp** [comment]
For:

> A newline delimited JSON writer and parser.

I think we can use [njdson](https://github.com/maxogden/ndjson#ndjsonserialize--ndjsonstringify) instead. As long as your db library can provide streams (or you can turn them into streams) you can do:

```js

app.get('/todos.ndjson', function(request, response){
  db.query('select * from foo')
    .pipe(ndjson.serialize())
    .pipe(response);
});
```

**Comment by matthewp** [comment]
The demo server is available at https://github.com/donejs/demo-streaming-dev-server  I'm adding an issue to upgrade the server so that it pulls todos from a real database.

**Comment by Xuefeng-Zhu** [comment]
@justinbmeyer Talk to on HackIllinois. It seems that what the project is trying to do is server push, which is implemented in http2 standard 

https://www.igvita.com/2013/06/12/innovating-with-http-2.0-server-push/

**Comment by justinbmeyer** [comment]
Thanks Xuefeng. This isn't the same as server push. Stop by 3017 tomorrow if you want an explanation why.

**Comment by justinbmeyer** [comment]
<img width="790" alt="cursor_and_v5_key" src="https://cloud.githubusercontent.com/assets/78602/23341354/91af11b8-fc0b-11e6-929a-45838e2b1233.png">

**Comment by leoj3n** [comment]
This, is a fine idea.

Is my understanding correct, that SSR is what enables this to work, and it would not be possible without the SSR brokering the transaction? In that case, it makes using SSR that much more convincing. I don't see why this should cause a problem with javascript spidering search engines, but if it did I would imagine the solution could be a trigger offered by the likes of Google, that allows you to tell the engine your page is *now* complete; not sure if that exists or is necessary though, and maybe I'm overthinking it.

**Comment by matthewp** [comment]
@leoj3n There are 2 parts. One is streaming SSR. The other is streaming API requests. The latter does not require that you use SSR. It will be available as a can-connect plugin ([can-connect-ndjson](https://github.com/canjs/can-connect-ndjson)) that can be used with any can project. Server rendered or not.

**Comment by justinbmeyer** [comment]
@leoj3n google (or anything consuming the `http` response) would know to wait until the response is complete anyway.

**Comment by leoj3n** [comment]
That is so cool. Very elegant. I am going to have to play with this, and possibly rig up an objective speed comparison test.

**Comment by matthewp** [comment]
For a demo I would have something with 1) A header 2) A sidebar 3) A list of something (search results is a good candidate since search queries are usually slower)

We could slow down the query so that you can see the header and styles being applied, the sidebar showing up, and then the results appending.  

This is for SSR. Client-side streaming might have a better demo for it (although I think this isn't a bad one for that either).

**Comment by matthewp** [comment]
# Testing Streaming Approaches

Last week I did some testing of [two approaches](https://github.com/donejs/donejs-streaming-test-comparison) to streaming with HTTP2. In both methods:

* The JavaScript is pushed.
* The data requests are pushed.
* 100 items are streamed from the API, 1 every 10ms.

The difference is in how the DOM rendering happens.

## Traditional SPA with streaming data

The first approach was a traditional SPA with streaming data. The timeline looks like this:

![screen shot 2017-05-10 at 10 06 22 am](https://cloud.githubusercontent.com/assets/361671/25903270/eaf0e5de-3569-11e7-935e-d2b7a94ae051.png)

Since the data is streamed we only need to append to the list. CanJS can do this very quickly.

## Incremental Rendering

In this method **instructions** on how to render are streamed from the server (along with the data). The timeline looks like this:

![screen shot 2017-05-10 at 10 06 46 am](https://cloud.githubusercontent.com/assets/361671/25903594/deecbe4c-356a-11e7-94d2-3a8985240ceb.png)

This method is advantageous because instructions come in *incrementally* and *asynchronously*. This is especially good for slower cpus (such as some phones).

# Conclusions

Some conclusions I drew from these tests are that:

* The slowest part of the app is the blocker when streaming. If the slowest part of your app is the data requests, then either method is about the same.  But if the JavaScript payload is the slowest part, the incremental rendering approach will be better.
* Slower CPUs are affected by the amount of JavaScript executed. This favors the incremental approach which:
  * Has a smaller initial payload.
  * Modifies the DOM incrementally (as instructions come in), asynchronously.
* Incremental rendering can get to first-paint faster as it doesn't have to wait on a large bundle to execute.

**Comment by matthewp** [comment]
# Next Steps

I think regardless of whether the incremental rendering approach becomes a real thing that we use in DoneJS apps (and it might!) there are still some important changes that would be useful. 

With that being said I think we should:

1. Add HTTP2 support to done-serve
1. Change steal-tools to export it's dependency graph (to include a mapping of bundles to all of the split bundles).
1. Update done-ssr, using the info from (2) to HTTP2 push (when in an HTTP2 setting) the JavaScript.
1. Update done-ssr to HTTP2 the data requests.
1. Create the incremental rendering as an option in done-ssr (or possibly as an external plugin, if we want to avoid over-committing to this approach).

**Comment by matthewp** [comment]
Going to close in favor of https://github.com/donejs/donejs/issues/787, of course we will being making future streaming enhancements in the future.
